name: VekProducer CI/CD Workflow

on:
  push:
    tags: ['v*', 'v*.*', 'v*.*.*']

jobs:
  ci:
    uses: VekRest/.github/workflows/main-template.yml@main
    with:
      sonar_project_key: vekproducer
      sonar_org: vekrest
      dockerhub_repo: vekrest-vekproducer
      maven_group: com.vekrest.vekproducer
      maven_artifact: vekproducer
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      release_token: ${{ secrets.RELEASE_TOKEN }}
